#!/usr/bin/env python3
"""Create structured China Daily corpus notes from public URLs without saving full text."""

from __future__ import annotations

import argparse
import html
import re
import time
import urllib.error
import urllib.request
from pathlib import Path


USER_AGENT = "CodexSkillResearch/1.0 (+style notes only; no full-text storage)"
REQUEST_TIMEOUT = 20
REQUEST_DELAY_SECONDS = 1.0


def skill_root() -> Path:
    return Path(__file__).resolve().parents[1]


def read_urls(args: argparse.Namespace) -> list[str]:
    urls: list[str] = []
    if args.urls_file:
        urls.extend(
            line.strip()
            for line in Path(args.urls_file).read_text(encoding="utf-8").splitlines()
            if line.strip() and not line.strip().startswith("#")
        )
    urls.extend(args.urls)
    return list(dict.fromkeys(urls))


def fetch_metadata(url: str) -> dict[str, str]:
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(request, timeout=REQUEST_TIMEOUT) as response:
        raw = response.read(300_000).decode("utf-8", errors="replace")

    title = ""
    match = re.search(r"<title[^>]*>(.*?)</title>", raw, flags=re.I | re.S)
    if match:
        title = re.sub(r"\s+", " ", html.unescape(match.group(1))).strip()
        title = re.sub(r"\s*-\s*Chinadaily.*$", "", title, flags=re.I)

    date = ""
    for pattern in [
        r"(\d{4}-\d{2}-\d{2})",
        r"(\d{4}/\d{2}/\d{2})",
        r"(\d{4}\.\d{2}\.\d{2})",
    ]:
        match = re.search(pattern, raw)
        if match:
            date = match.group(1)
            break

    section = ""
    section_match = re.search(r"(?:channel|section)[\"']?\s*[:=]\s*[\"']([^\"']+)", raw, flags=re.I)
    if section_match:
        section = html.unescape(section_match.group(1)).strip()

    return {"title": title or "[title not found]", "date": date or "[date not found]", "section": section}


def record_for(url: str, number: int, metadata: dict[str, str], error: str | None = None) -> str:
    title = metadata.get("title", "[title not found]")
    date = metadata.get("date", "[date not found]")
    section = metadata.get("section", "")
    note = error or "Metadata collected; add human style observations after reading."
    return f"""### {number}. {title}

- URL: {url}
- Publication date: {date}
- Section / column: {section or "[not identified]"}
- Topic category: [add category]
- Article type: [news / feature / event notice / trend / photo item]
- Headline pattern: [add observation]
- Lead pattern: [add observation]
- Paragraph structure: [add observation]
- Quote usage: [add observation]
- Attribution pattern: [add observation]
- Background information placement: [add observation]
- Cultural explanation strategy: [add observation]
- International audience adaptation: [add observation]
- Tone and diction observations: [add observation]
- Useful writing pattern summary: {note}
- Do-not-copy note: Do not save full text or copy article-specific phrasing.
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("urls", nargs="*", help="China Daily public article URL(s).")
    parser.add_argument("--urls-file", help="Text file containing one URL per line.")
    parser.add_argument(
        "--output",
        default=str(skill_root() / "references" / "china_daily_corpus_notes.md"),
        help="Markdown notes output path.",
    )
    parser.add_argument("--append", action="store_true", help="Append records instead of replacing file.")
    args = parser.parse_args()

    output = Path(args.output)
    if not output.is_absolute():
        output = (Path.cwd() / output).resolve()
    output.parent.mkdir(parents=True, exist_ok=True)

    urls = read_urls(args)
    if not urls:
        template = skill_root() / "templates" / "corpus_note_template.md"
        print("No URLs supplied. Add URLs as arguments or with --urls-file.")
        print(f"Use the template at {template}")
        return 0

    records: list[str] = []
    for idx, url in enumerate(urls, 1):
        try:
            metadata = fetch_metadata(url)
            records.append(record_for(url, idx, metadata))
        except (urllib.error.URLError, TimeoutError, OSError) as exc:
            records.append(record_for(url, idx, {"title": "[fetch failed]", "date": "[unknown]"}, str(exc)))
        time.sleep(REQUEST_DELAY_SECONDS)

    header = "# China Daily Public Corpus Notes\n\nGenerated by `scripts/collect_china_daily_samples.py`.\n\n"
    text = "\n".join(records).rstrip() + "\n"
    if args.append and output.exists():
        with output.open("a", encoding="utf-8") as fh:
            fh.write("\n" + text)
    else:
        output.write_text(header + text, encoding="utf-8")

    print(f"Wrote {len(records)} record(s) to {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

