#!/usr/bin/env python3
"""Extract paragraphs and tables from local DOCX writing guides into Markdown."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


def skill_root() -> Path:
    return Path(__file__).resolve().parents[1]


def default_project_root() -> Path:
    root = skill_root()
    return root.parents[2] if len(root.parents) >= 3 else Path.cwd()


def load_docx():
    try:
        from docx import Document  # type: ignore
    except ImportError as exc:
        raise SystemExit(
            "Missing dependency: python-docx. Install with `pip install python-docx` "
            "or run this script in a Python environment that already provides it."
        ) from exc
    return Document


def find_docx_files(project_root: Path, explicit_paths: list[str]) -> list[Path]:
    if explicit_paths:
        return [Path(p).expanduser().resolve() for p in explicit_paths]

    skill_dir = skill_root().resolve()
    files: list[Path] = []
    for path in project_root.rglob("*.docx"):
        resolved = path.resolve()
        if skill_dir in resolved.parents:
            continue
        if path.name.startswith("~$"):
            continue
        files.append(path)
    return sorted(files)


def extract_document(path: Path, Document, project_root: Path) -> str:
    doc = Document(path)
    try:
        display_path = path.resolve().relative_to(project_root)
    except ValueError:
        display_path = path
    lines: list[str] = [f"## Source: `{display_path.as_posix()}`", ""]

    paragraphs = [p.text.strip() for p in doc.paragraphs if p.text.strip()]
    lines.append(f"- Paragraphs extracted: {len(paragraphs)}")
    lines.append(f"- Tables extracted: {len(doc.tables)}")
    lines.append("")

    if paragraphs:
        lines.append("### Paragraphs")
        lines.append("")
        for idx, text in enumerate(paragraphs, 1):
            lines.append(f"{idx}. {text}")
        lines.append("")

    if doc.tables:
        lines.append("### Tables")
        lines.append("")
        for t_idx, table in enumerate(doc.tables, 1):
            lines.append(f"#### Table {t_idx}")
            for row in table.rows:
                cells = [cell.text.strip().replace("\n", " / ") for cell in row.cells]
                if any(cells):
                    lines.append("- " + " | ".join(cells))
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("docx", nargs="*", help="Optional DOCX path(s). If omitted, scan project root.")
    parser.add_argument("--project-root", default=str(default_project_root()), help="Project root to scan.")
    parser.add_argument(
        "--output",
        default=str(skill_root() / "references" / "extracted_docx_style_guide.md"),
        help="Markdown output path.",
    )
    args = parser.parse_args()

    Document = load_docx()
    project_root = Path(args.project_root).expanduser().resolve()
    output = Path(args.output).expanduser()
    if not output.is_absolute():
        output = (Path.cwd() / output).resolve()
    output.parent.mkdir(parents=True, exist_ok=True)

    files = find_docx_files(project_root, args.docx)
    lines = [
        "# Extracted Docx Style Guide",
        "",
        "Generated by `scripts/extract_docx_rules.py`.",
        "",
        "This extraction is for rule analysis. Do not paste full source text into `SKILL.md`.",
        "",
    ]

    if not files:
        lines.extend(
            [
                "No `.docx` files were found.",
                "",
                "docx-derived rules pending.",
                "",
            ]
        )
    else:
        for file_path in files:
            lines.append(extract_document(file_path, Document, project_root))

    output.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"Wrote {output}")
    print(f"DOCX files processed: {len(files)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
